#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return



alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rename='perl-rename'
alias tmux='tmux -u -2 -f ~/.config/tmux.conf'
alias pdfview='apvlv'
alias emacs='emacs -nw'
alias pacman='pacman --color always'
alias gcc='gcc -fno-diagnostics-show-caret'
alias g++='g++ -fno-diagnostics-show-caret'
alias rae="dict --host localhost"

# Using .config as config directory
alias alpine='alpine -p ~/.config/pinerc'
alias mutt='mutt -F ~/.config/muttrc'
alias startx='startx ~/.config/xinitrc'
alias ncmpcpp='ncmpcpp --config ~/.config/ncmpcpp'
alias finch='finch --config ~/.config/purple/'
alias irssi='irssi --config ~/.config/irssi --home=~/.local/share/irssi'

#start x at login
if [ "$(tty)" = "/dev/tty1" -o "$(tty)" = "/dev/vc/1" ]; then
	#startxfce4 
	startx 
fi

#PS1='[\u@\h \W]\$ '
PS1='$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#I") "$PWD")\[\033[00;32m\]\h@\u:\W\$\[\033[00m\] '


export TERM=screen-256color
#man pages with color
export LESS_TERMCAP_mb=$'\E[01;31m' # begin blinking
export LESS_TERMCAP_md=$'\E[01;37m' # begin bold
export LESS_TERMCAP_me=$'\E[0m' # end mode
export LESS_TERMCAP_se=$'\E[0m' # end stand-out mode
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin stand-out mode - info box
export LESS_TERMCAP_ue=$'\E[0m' # end underline
export LESS_TERMCAP_us=$'\E[00;32m' # begin underline

export EDITOR=vim

shopt -s checkwinsize
#Todas las screens comparten el mismo historial
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s histappend
#export PROMPT_COMMAND="$PROMPT_COMMAND:history -a: history -n"
#export HISTCONTROL=ignorespace:erasedups
export HISTCONTROL=erasedups
export HISTIGNORE="clear:exit:[bf]g:ls:cd:ls *:cd *:  *"
export HISTSIZE=10000

d=~/.config/dircolors
test -r $d && eval "$(dircolors $d)"

#vi bindings
set -o vi

#don't clear the screen on exit
export PAGER='less -X'

export PATH=$PATH:~/usr/bin
export C_INCLUDE_PATH=$C_INCLUDE_PATH:~/usr/include
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:~/usr/include
export LIBRARY_PATH=$LIBRARY_PATH:~/usr/lib


function proxy(){
	proxyserver=192.168.0.120
	port=3128
	export http_proxy="http://$username:$password@$proxyserver:$port"
	export https_proxy=$http_proxy
	export ftp_proxy=$http_proxy
	export rsync_proxy=$http_proxy
	export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
	echo -e "\nProxy environment variable set."
}
function proxyoff(){
	unset HTTP_PROXY
	unset http_proxy
	unset HTTPS_PROXY
	unset https_proxy
	unset FTP_PROXY
	unset ftp_proxy
	unset RSYNC_PROXY
	unset rsync_proxy
	echo -e "\nProxy environment variable removed."
}
