set nowritebackup
set nobackup
set noswapfile
"set verbose=9
"tab
set autoindent
set tabstop=4
"set expandtab
set shiftwidth=4

set showcmd

set nu "line numbers
syntax on "highlighting
if &diff
	syntax off
endif
"set hlsearch "resalt found text
"set mouse=a
set t_Co=256

colorscheme desert
set printoptions=paper:a4

"keycodes
set <F1>=[M
set <F2>=[N
set <F3>=[O
set <F4>=[P
set <F5>=[Q
set <F6>=[R
set <F7>=[S
set <F8>=[T
set <F9>=[U
set <F10>=[V
set <F11>=[W
set <F12>=[X

"compilar
set makeprg=clear\ &&\ g++\ -W{all,extra,pedantic}\ -ggdb\ -std=c++11\ %
map <F9> :write <Return> :make <Return>
"moverse por los errores
map [q :cnext <Return>
map ]q :cprev <Return>

"usar templates segun extension del archivo
autocmd! BufNewFile * silent! 0r ~/.vim/skeletons/template.%:e
autocmd! BufNewFile,BufRead *.tex set filetype=tex

"autocomplete commands
set wildmode=longest,list

"open doc files
autocmd BufReadPre *.doc set ro
autocmd BufReadPost *.doc %!antiword -f -i 1 -w 0 "%"

"for autocompletion of code (clang)
let g:clang_complete_auto = 0
"parameters of functions
let g:clang_snippets = 1
let g:clang_snippets_engine = 'clang_complete'
let g:clang_sort_algo='alpha'

"identado (clang-format)
set formatprg=clang-format\ 2>/dev/null
"map <C-K> :pyf /usr/share/clang/clang-format.py<cr>
"imap <C-K> <c-o>:pyf /usr/share/clang/clang-format.py<cr>


" OmniCppComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1 " show function parameters
let OmniCpp_MayCompleteDot = 1 " autocomplete after .
let OmniCpp_MayCompleteArrow = 1 " autocomplete after ->
let OmniCpp_MayCompleteScope = 1 " autocomplete after ::
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
"set completeopt=menuone,menu,longest,preview
set completeopt=menuone,menu,longest

"to set omnicpp
au BufNewFile,BufRead,BufEnter *.cpp,*.hpp set omnifunc=omni#cpp#complete#Main

"let $PAGER=''
"nmap K :Man <C-R>=expand(\\"<cword>\\")<CR><CR> -\""

runtime ftplugin/man.vim

function! s:insert_gates()
	let gatename = substitute(toupper(expand("%:t")), "\\.", "_", "g")
	execute "normal! i#ifndef " . gatename
	execute "normal! o#define " . gatename . " "
	execute "normal! Go#endif /* " . gatename . " */"
	normal! kk
	endfunction
autocmd BufNewFile *.{h,hpp} call <SID>insert_gates()


set path+=../header
"open the #include file in a new vertical window
map f :vertical botright sfind <cfile><CR>


"cscope
if has("cscope")
	set cscopeprg=/usr/bin/cscope
	set cscopetagorder=0
	set cscopetag
	set nocscopeverbose
	" add any database in current directory
	if filereadable("cscope.out")
		cs add cscope.out
	" else add database pointed to by environment
	elseif $CSCOPE_DB != ""
		cs add $CSCOPE_DB
	endif
	set cscopeverbose
endif

nmap <C-c>s 
	\:cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-c>g 
	\:cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-c>c 
	\:cs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-c>t 
	\:cs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-c>e 
	\:cs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-c>f 
	\:cs find f <C-R>=expand("<cfile>")<CR><CR>
nmap <C-c>i 
	\:cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap <C-c>d 
	\:cs find d <C-R>=expand("<cword>")<CR><CR>

"latex plugin
filetype plugin on
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'

let g:Tex_SmartKeyBS = 0
let g:Tex_SmartKeyQuote = 0
let g:Tex_SmartKeyDot = 0

let g:Imap_UsePlaceHolders = 0

let g:Tex_Leader = '`tex'
let g:Tex_Leader2 = ',tex'


"syntastic
"let g:syntastic_mode_map = { "mode": "pasive", "active_filetypes": [], "passive_filetypes": ["cpp"] }
let g:syntastic_mode_map = { "mode": "pasive", "active_filetypes": ["foo"], "passive_filetypes": ["cpp"] }

let g:pydiction_location = '/usr/share/pydiction/complete-dict'

"no analiza
let g:syntastic_check_on_wq = 0


"syntastic
nmap ]l :lnext<CR>
nmap [l :lprev<CR>
nmap R :call Rae(expand("<cword>"))<CR><CR>

function! Rae(palabra)
	new
	:exec printf('0read !rae %s | nocolor.sh', a:palabra)
	0
endfunction


" Ignore Uppercase words when spell checking
fun! IgnoreUppercaseSpell()
  syn match Uppercase /\<[A-Z][a-z]*\>/ contains=@NoSpell transparent
  syn cluster Spell add=Uppercase
endfun
"autocmd BufRead,BufNewFile * :call IgnoreUppercaseSpell()

"Gdiff open in vertical
set diffopt=filler,vertical
