typeset -U path PATH
path=($path ${HOME}/usr/bin ${HOME}/.local/bin)
export PATH

export C_INCLUDE_PATH=${C_INCLUDE_PATH}:${HOME}/.local/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:${HOME}/.local/include
export PYTHONPATH=${PYTHONPATH}:${HOME}/.local/lib/python3.10/:${HOME}/usr/lib/python/
export LIBRARY_PATH=${LIBRARY_PATH}:${HOME}/.local/lib:${HOME}/.local/lib64:
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/.local/lib:${HOME}/.local/lib64
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${HOME}/.local/lib/pkgconfig:${HOME}/.local/lib64/pkgconfig

export LC_ALL=en_US.utf8

export IPYTHONDIR="${HOME}/.config/ipython/"
export GIMP2_DIRECTORY="${HOME}/.local/share/gimp"
export GIMP2_SYSCONFDIR="${HOME}/.config/gimp"

export EDITOR=nvim
export VISUAL=nvim

export MANPAGER='nvim +Man!'
export PYTHONDONTWRITEBYTECODE="non empty string"
