#plugins=(dotnet extract fzf gpg-agent universalarchive vi-mode)

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
source "$HOME/.config/fzf.config"

source "$HOME/.config/zsh/alias"
source "$HOME/.config/zsh/history"

setopt rm_star_silent
# vi mode
bindkey -v
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

autoload -U colors && colors
eval "$(dircolors $HOME/.config/dircolors)"
PROMPT="%{$bg[blue]$fg_bold[cyan]%}%n:%2~%(!.#.$)%{$reset_color%} "

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
autoload -Uz compinit && compinit

when
